# Generated by Django 3.1.2 on 2020-10-14 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('gender_identity', models.CharField(choices=[(1, 'Agender'), (2, 'Androgyne'), (3, 'Androgynous'), (4, 'Bigender'), (5, 'Cis'), (6, 'Cisgender'), (7, 'Cis Female'), (8, 'Cis Male'), (9, 'Cis Man'), (10, 'Cis Woman'), (11, 'Cisgender Female'), (12, 'Cisgender Male'), (13, 'Cisgender Man'), (14, 'Cisgender Woman'), (15, 'Female'), (16, 'Female to Male'), (17, 'FTM'), (18, 'Gender Fluid'), (19, 'Gender F*ck'), (20, 'Gender Nonconforming'), (21, 'Gender Questioning'), (22, 'Gender Variant'), (23, 'Genderqueer'), (24, 'Male'), (25, 'Male to Female'), (26, 'MTF'), (27, 'Neither'), (28, 'Neutrois'), (29, 'Non-binary'), (30, 'Other'), (31, 'Pangender'), (32, 'Trans'), (33, 'Trans Man'), (34, 'Trans Person'), (35, 'Trans Woman'), (36, 'Transfeminine'), (37, 'Transgender'), (38, 'Transgender Female'), (39, 'Transgender Male'), (40, 'Transgender Man'), (41, 'Transgender Person'), (42, 'Transgender Woman'), (43, 'Transmasculine'), (44, 'Transsexual'), (45, 'Transsexual Female'), (46, 'Transsexual Male'), (47, 'Transsexual Man'), (48, 'Transsexual Person'), (49, 'Transsexual Woman'), (50, 'Two Spirit')], max_length=50)),
                ('show_me', models.CharField(choices=[('W', 'Women'), ('M', 'Men'), ('E', 'Everyone')], max_length=1)),
                ('same_orientation_first', models.BooleanField()),
                ('last_sign_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('dislikes', models.ManyToManyField(related_name='dislike_target', to='frontpage.User')),
                ('likes', models.ManyToManyField(related_name='like_target', to='frontpage.User')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.user')),
            ],
        ),
    ]
