# Generated by Django 3.1.2 on 2020-10-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='alt',
            field=models.CharField(default='', max_length=140),
        ),
    ]
